version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql2
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crone
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d


  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9696:9696"
    networks:
      - springboot-db-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/crone
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb


networks:
  springboot-db-net:

volumes:
  db_data:
